parent=keycloak
import=common/keycloak
styles=css/style.css

# Habilitar internacionalización
locales=es,en
# Idioma por defecto si el navegador no especifica uno
defaultLocale=es

# Indicar que use nuestro propio archivo de traducciones
messages=messages